### ISSUE TITLE
point fifengine.net via cname entry to this repo

### ISSUE THREAD

**Issue by jakoch** [fifengine/fifeweb#6]
It would be nice to redirect the URL [fifengine.net](fifengine.net) via a CNAME/ALIAS entry to this repo/gh-pages.
The website is then served from GitHub and we can make changes by committing to this repo.
An additional server or webhosting is then no longer needed.
Serving from GitHub will not cause a problem, because it's static HTML content.

https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by prock-fife** [comment]
done via 8c7d19b5310913e6a9ab4fc70ef3dc969c570d05
